services:
    akeneo.job.controller.index_action:
        class: 'Akeneo\Platform\Job\Infrastructure\Controller\IndexAction'
        public: true
        arguments:
            - '@Akeneo\Platform\Job\Application\SearchJobExecution\SearchJobExecutionHandler'

    akeneo.job.controller.get_job_types_action:
        class: 'Akeneo\Platform\Job\Infrastructure\Controller\GetJobTypesAction'
        public: true
        arguments:
            - '@Akeneo\Platform\Job\Domain\Query\FindJobTypesInterface'

    akeneo.job.controller.get_job_users_action:
        class: 'Akeneo\Platform\Job\Infrastructure\Controller\GetJobUsersAction'
        public: true
        arguments:
            - '@Akeneo\Platform\Job\Domain\Query\FindJobUsersInterface'
